# Generated by Django 4.1.1 on 2022-10-06 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ar_dpt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='ArDpt_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'customers_departamento_ambiente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AreasModel',
            fields=[
                ('id', models.BigAutoField(db_column='ar_id', primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(db_column='ar_nombre_area', max_length=255, verbose_name="Area's name")),
                ('ubicacion', models.JSONField(db_column='ar_ubicacion_area', null=True, verbose_name="Area's location")),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
            ],
            options={
                'db_table': 'customers_Ambientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Con_Dpt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='ConDpt_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'customers_contactos_departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactosModel',
            fields=[
                ('id', models.BigAutoField(db_column='con_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='con_nombre', max_length=255, verbose_name="Contact's name")),
                ('apellidos', models.CharField(db_column='con_apellidos', max_length=255, verbose_name="Contact's last name")),
                ('dni', models.CharField(blank=True, db_column='con_numero_dni', max_length=255, null=True, unique=True, verbose_name="Contact's DNI number")),
                ('numero_telefono', models.CharField(blank=True, db_column='con_numero_telefono', max_length=255, null=True, verbose_name='Contact phone number')),
                ('correo', models.CharField(blank=True, db_column='con_correo_electronico', max_length=255, null=True, unique=True, verbose_name='Contact email address')),
                ('cargo', models.CharField(blank=True, db_column='con_cargo', max_length=255, null=True, verbose_name='Job')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
            ],
            options={
                'db_table': 'customers_Contactos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.BigAutoField(db_column='dpt_id', primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(db_column='dpt_nombre_departamento', max_length=255, verbose_name="Headquarters's name")),
                ('direccion_departamento', models.CharField(blank=True, db_column='dpt_direccion_departamento', max_length=255, null=True, verbose_name="Headquarters's address")),
                ('pais_departamento', models.CharField(blank=True, db_column='dpt_pais', max_length=255, null=True, verbose_name='Country where the headquarters belongs')),
                ('departamento_departamento', models.CharField(blank=True, db_column='dpt_departamento', max_length=255, null=True, verbose_name='Department to which the headquarters belongs')),
                ('provincia_departamento', models.CharField(blank=True, db_column='dpt_provincia', max_length=255, null=True, verbose_name='Province to which the headquarters belongs')),
                ('distrito_departamento', models.CharField(blank=True, db_column='dpt_distrito', max_length=255, null=True, verbose_name='District to which the headquarters belongs')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('contactos', models.ManyToManyField(through='Customer.Con_Dpt_Model', to='Customer.contactosmodel')),
                ('members', models.ManyToManyField(through='Customer.Ar_dpt_Model', to='Customer.areasmodel')),
            ],
            options={
                'db_table': 'customers_Depatamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dpt_org_Model',
            fields=[
                ('id', models.BigAutoField(db_column='DptOrg_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.departamentomodel')),
            ],
            options={
                'db_table': 'customers_organizacion_departamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizacionModel',
            fields=[
                ('id', models.BigAutoField(db_column='org_id', primary_key=True, serialize=False)),
                ('ruc', models.CharField(blank=True, db_column='org_ruc', max_length=12, null=True, unique=True, verbose_name="Organization's ruc number")),
                ('razon_social', models.CharField(blank=True, db_column='org_razon_social', max_length=255, unique=True, verbose_name="Organization's name")),
                ('nombre_comercial', models.CharField(blank=True, db_column='org_nombre_comercial', max_length=255, null=True, unique=True, verbose_name="Organization's commercial name ")),
                ('tipo', models.CharField(blank=True, db_column='org_tipo', max_length=255, null=True, verbose_name="Organization's type")),
                ('ciiu', models.IntegerField(blank=True, db_column='org_ciiu', null=True, verbose_name="Organization's International Standard Industrial Classification")),
                ('direccion_legal', models.CharField(blank=True, db_column='org_direccion_legal', max_length=255, null=True, verbose_name="Organization's legal address")),
                ('pais_organizacion', models.CharField(blank=True, db_column='org_pais', max_length=255, null=True, verbose_name='Country where the organization belongs')),
                ('departamento_organizacion', models.CharField(blank=True, db_column='org_departamento', max_length=255, null=True, verbose_name='Department to which the organization belongs')),
                ('provincia_organizacion', models.CharField(blank=True, db_column='org_provincia', max_length=255, null=True, verbose_name='Province to which the organization belongs')),
                ('distrito_organizacion', models.CharField(blank=True, db_column='org_distrito', max_length=255, null=True, verbose_name='District to which the organization belongs')),
                ('is_enabled', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('members', models.ManyToManyField(through='Customer.Dpt_org_Model', to='Customer.departamentomodel')),
            ],
            options={
                'db_table': 'customers_Organizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Organizaciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.organizacionmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Departamentos_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.departamentomodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Contactos_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.contactosmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Areas_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.areasmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organizacionmodel',
            name='user',
            field=models.ManyToManyField(through='Customer.User_Organizaciones_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpt_org_model',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.organizacionmodel'),
        ),
        migrations.AddField(
            model_name='departamentomodel',
            name='user',
            field=models.ManyToManyField(through='Customer.User_Departamentos_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactosmodel',
            name='user',
            field=models.ManyToManyField(through='Customer.User_Contactos_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='con_dpt_model',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.contactosmodel'),
        ),
        migrations.AddField(
            model_name='con_dpt_model',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.departamentomodel'),
        ),
        migrations.AddField(
            model_name='areasmodel',
            name='user',
            field=models.ManyToManyField(through='Customer.User_Areas_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ar_dpt_model',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.areasmodel'),
        ),
        migrations.AddField(
            model_name='ar_dpt_model',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.departamentomodel'),
        ),
    ]
