# Generated by Django 3.2.6 on 2022-09-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ar_dpt_model',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='areasmodel',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='con_dpt_model',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactosmodel',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='departamentomodel',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dpt_org_model',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizacionmodel',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
