# Generated by Django 4.0.7 on 2022-09-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ar_dpt_model',
            table='customers_departamento_ambiente',
        ),
    ]
