# Generated by Django 4.1.1 on 2022-10-06 23:02

import User.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_rename_state_areasmodel_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalareasmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalcontactosmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartamentomodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalorganizacionmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
    ]
