# Generated by Django 3.2.6 on 2022-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20220923_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactosmodel',
            name='cargo',
            field=models.CharField(blank=True, db_column='con_cargo', max_length=255, null=True, verbose_name='Job'),
        ),
    ]
