# Generated by Django 4.1.5 on 2023-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
        ('Customer', '0003_alter_historicalareasmodel_options_and_more'),
    ]

    operations = [
    ]
