# Generated by Django 4.1.2 on 2022-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_historicalareasmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactosmodel',
            name='apellidos',
            field=models.CharField(blank=True, db_column='con_apellidos', default='---', max_length=255, null=True, verbose_name="Contact's last name"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='cargo',
            field=models.CharField(blank=True, db_column='con_cargo', default='---', max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='correo',
            field=models.CharField(blank=True, db_column='con_correo_electronico', default='---', max_length=255, null=True, verbose_name='Contact email address'),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='dni',
            field=models.CharField(blank=True, db_column='con_numero_dni', default='---', max_length=255, null=True, unique=True, verbose_name="Contact's DNI number"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='nombre',
            field=models.CharField(blank=True, db_column='con_nombre', default='---', max_length=255, null=True, verbose_name="Contact's name"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='numero_telefono',
            field=models.CharField(blank=True, db_column='con_numero_telefono', default='---', max_length=255, null=True, verbose_name='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='apellidos',
            field=models.CharField(blank=True, db_column='con_apellidos', default='---', max_length=255, null=True, verbose_name="Contact's last name"),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='cargo',
            field=models.CharField(blank=True, db_column='con_cargo', default='---', max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='correo',
            field=models.CharField(blank=True, db_column='con_correo_electronico', default='---', max_length=255, null=True, verbose_name='Contact email address'),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='dni',
            field=models.CharField(blank=True, db_column='con_numero_dni', db_index=True, default='---', max_length=255, null=True, verbose_name="Contact's DNI number"),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='nombre',
            field=models.CharField(blank=True, db_column='con_nombre', default='---', max_length=255, null=True, verbose_name="Contact's name"),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='numero_telefono',
            field=models.CharField(blank=True, db_column='con_numero_telefono', default='---', max_length=255, null=True, verbose_name='Contact phone number'),
        ),
    ]
