# Generated by Django 4.1.1 on 2022-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_contactosmodel_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactosmodel',
            name='cargo',
            field=models.CharField(db_column='con_cargo', max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='correo',
            field=models.CharField(db_column='con_correo_electronico', max_length=255, null=True, unique=True, verbose_name='Contact email address'),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='dni',
            field=models.CharField(db_column='con_numero_dni', max_length=255, null=True, unique=True, verbose_name="Contact's DNI number"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='numero_telefono',
            field=models.CharField(db_column='con_numero_telefono', max_length=255, null=True, verbose_name='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='departamento_departamento',
            field=models.CharField(db_column='dpt_departamento', max_length=255, null=True, verbose_name='Department to which the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='direccion_departamento',
            field=models.CharField(db_column='dpt_direccion_departamento', max_length=255, null=True, verbose_name="Headquarters's address"),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='distrito_departamento',
            field=models.CharField(db_column='dpt_distrito', max_length=255, null=True, verbose_name='District to which the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='pais_departamento',
            field=models.CharField(db_column='dpt_pais', max_length=255, null=True, verbose_name='Country where the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='provincia_departamento',
            field=models.CharField(db_column='dpt_provincia', max_length=255, null=True, verbose_name='Province to which the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='ciiu',
            field=models.IntegerField(db_column='org_ciiu', null=True, verbose_name="Organization's International Standard Industrial Classification"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='departamento_organizacion',
            field=models.CharField(db_column='org_departamento', max_length=255, null=True, verbose_name='Department to which the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='direccion_legal',
            field=models.CharField(db_column='org_direccion_legal', max_length=255, null=True, verbose_name="Organization's legal address"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='distrito_organizacion',
            field=models.CharField(db_column='org_distrito', max_length=255, null=True, verbose_name='District to which the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='nombre_comercial',
            field=models.CharField(db_column='org_nombre_comercial', max_length=255, null=True, unique=True, verbose_name="Organization's commercial name "),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='pais_organizacion',
            field=models.CharField(db_column='org_pais', max_length=255, null=True, verbose_name='Country where the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='provincia_organizacion',
            field=models.CharField(db_column='org_provincia', max_length=255, null=True, verbose_name='Province to which the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='ruc',
            field=models.CharField(db_column='org_ruc', max_length=12, null=True, unique=True, verbose_name="Organization's ruc number"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='tipo',
            field=models.CharField(db_column='org_tipo', max_length=255, null=True, verbose_name="Organization's type"),
        ),
    ]
