# Generated by Django 4.1.2 on 2022-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_contactosmodel_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactosmodel',
            name='dni',
            field=models.CharField(blank=True, db_column='con_numero_dni', default='---', max_length=255, null=True, verbose_name="Contact's DNI number"),
        ),
        migrations.AlterField(
            model_name='historicalcontactosmodel',
            name='dni',
            field=models.CharField(blank=True, db_column='con_numero_dni', default='---', max_length=255, null=True, verbose_name="Contact's DNI number"),
        ),
    ]
