# Generated by Django 4.1.1 on 2022-09-26 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0004_alter_contactosmodel_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacionmodel',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
