# Generated by Django 4.1.1 on 2022-09-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0005_organizacionmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacionmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='User_Organizaciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.organizacionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organizacionmodel',
            name='user',
            field=models.ManyToManyField(through='Customer.User_Organizaciones_Model', to=settings.AUTH_USER_MODEL),
        ),
    ]
