# Generated by Django 4.1.1 on 2022-09-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_user_departamentos_model_departamentomodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_departamentos_model',
            old_name='departamento',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='user_departamentos_model',
            old_name='user',
            new_name='model_user',
        ),
        migrations.RenameField(
            model_name='user_organizaciones_model',
            old_name='organizacion',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='user_organizaciones_model',
            old_name='user',
            new_name='model_user',
        ),
    ]
