# Generated by Django 4.1.1 on 2022-09-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_alter_areasmodel_options_alter_areasmodel_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasmodel',
            options={'ordering': ['id']},
        ),
    ]
