# Generated by Django 4.0.7 on 2022-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_alter_areasmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='areasmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='areasmodel',
            name='nombre_area',
            field=models.CharField(blank=True, db_column='ar_nombre_area', max_length=255, verbose_name="Area's name"),
        ),
        migrations.AlterField(
            model_name='areasmodel',
            name='ubicacion',
            field=models.JSONField(blank=True, db_column='ar_ubicacion_area', verbose_name="Area's location"),
        ),
        migrations.AlterField(
            model_name='con_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='apellidos',
            field=models.CharField(blank=True, db_column='con_apellidos', max_length=255, verbose_name="Contact's last name"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='cargo',
            field=models.CharField(blank=True, db_column='con_cargo', max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='correo',
            field=models.CharField(blank=True, db_column='con_correo_electronico', max_length=255, null=True, unique=True, verbose_name='Contact email address'),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='dni',
            field=models.CharField(blank=True, db_column='con_numero_dni', max_length=255, null=True, unique=True, verbose_name="Contact's DNI number"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='nombre',
            field=models.CharField(blank=True, db_column='con_nombre', max_length=255, verbose_name="Contact's name"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='numero_telefono',
            field=models.CharField(blank=True, db_column='con_numero_telefono', max_length=255, null=True, verbose_name='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='departamento_departamento',
            field=models.CharField(blank=True, db_column='dpt_departamento', max_length=255, null=True, verbose_name='Department to which the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='direccion_departamento',
            field=models.CharField(blank=True, db_column='dpt_direccion_departamento', max_length=255, null=True, verbose_name="Headquarters's address"),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='distrito_departamento',
            field=models.CharField(blank=True, db_column='dpt_distrito', max_length=255, null=True, verbose_name='District to which the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='nombre_departamento',
            field=models.CharField(blank=True, db_column='dpt_nombre_departamento', max_length=255, verbose_name="Headquarters's name"),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='pais_departamento',
            field=models.CharField(blank=True, db_column='dpt_pais', max_length=255, null=True, verbose_name='Country where the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='provincia_departamento',
            field=models.CharField(blank=True, db_column='dpt_provincia', max_length=255, null=True, verbose_name='Province to which the headquarters belongs'),
        ),
        migrations.AlterField(
            model_name='dpt_org_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='ciiu',
            field=models.IntegerField(blank=True, db_column='org_ciiu', null=True, verbose_name="Organization's International Standard Industrial Classification"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='departamento_organizacion',
            field=models.CharField(blank=True, db_column='org_departamento', max_length=255, null=True, verbose_name='Department to which the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='direccion_legal',
            field=models.CharField(blank=True, db_column='org_direccion_legal', max_length=255, null=True, verbose_name="Organization's legal address"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='distrito_organizacion',
            field=models.CharField(blank=True, db_column='org_distrito', max_length=255, null=True, verbose_name='District to which the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='nombre_comercial',
            field=models.CharField(blank=True, db_column='org_nombre_comercial', max_length=255, null=True, unique=True, verbose_name="Organization's commercial name "),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='pais_organizacion',
            field=models.CharField(blank=True, db_column='org_pais', max_length=255, null=True, verbose_name='Country where the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='provincia_organizacion',
            field=models.CharField(blank=True, db_column='org_provincia', max_length=255, null=True, verbose_name='Province to which the organization belongs'),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='razon_social',
            field=models.CharField(blank=True, db_column='org_razon_social', max_length=255, unique=True, verbose_name="Organization's name"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='ruc',
            field=models.CharField(blank=True, db_column='org_ruc', max_length=12, null=True, unique=True, verbose_name="Organization's ruc number"),
        ),
        migrations.AlterField(
            model_name='organizacionmodel',
            name='tipo',
            field=models.CharField(blank=True, db_column='org_tipo', max_length=255, null=True, verbose_name="Organization's type"),
        ),
        migrations.AlterField(
            model_name='user_areas_model',
            name='registerd_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user_departamentos_model',
            name='registerd_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user_organizaciones_model',
            name='registerd_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
