# Generated by Django 4.0.7 on 2022-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_ar_dpt_model_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='areasmodel',
            name='nombre_area',
            field=models.CharField(db_column='ar_nombre_area', max_length=255, verbose_name="Area's name"),
        ),
        migrations.AlterField(
            model_name='con_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='apellidos',
            field=models.CharField(db_column='con_apellidos', max_length=255, verbose_name="Contact's last name"),
        ),
        migrations.AlterField(
            model_name='contactosmodel',
            name='nombre',
            field=models.CharField(db_column='con_nombre', max_length=255, verbose_name="Contact's name"),
        ),
        migrations.AlterField(
            model_name='departamentomodel',
            name='nombre_departamento',
            field=models.CharField(db_column='dpt_nombre_departamento', max_length=255, verbose_name="Headquarters's name"),
        ),
        migrations.AlterField(
            model_name='dpt_org_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
