# Generated by Django 4.0.7 on 2022-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_alter_ar_dpt_model_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='con_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='dpt_org_model',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
