# Generated by Django 4.0.7 on 2022-09-28 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_alter_ar_dpt_model_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 17, 45, 57, 163661, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='con_dpt_model',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 17, 45, 57, 163661, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='dpt_org_model',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 17, 45, 57, 163661, tzinfo=utc), editable=False, null=True),
        ),
    ]
