# Generated by Django 4.0.7 on 2022-09-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Customer', '0019_alter_ar_dpt_model_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Contactos_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='contactosmodel',
            name='user',
            field=models.ManyToManyField(through='Customer.User_Contactos_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_contactos_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.contactosmodel'),
        ),
        migrations.AddField(
            model_name='user_contactos_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
