# Generated by Django 4.1.1 on 2022-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_user_contactos_model_contactosmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasmodel',
            name='ubicacion',
            field=models.JSONField(db_column='ar_ubicacion_area', null=True, verbose_name="Area's location"),
        ),
    ]
