# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tubos_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_sistemas_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.sistemamodel'),
        ),
        migrations.AddField(
            model_name='user_sistemas_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tubomodel',
            name='users',
            field=models.ManyToManyField(through='Machine.User_tubos_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stm_tb_model',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.sistemamodel'),
        ),
        migrations.AddField(
            model_name='stm_tb_model',
            name='tubo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.tubomodel'),
        ),
        migrations.AddField(
            model_name='sistemamodel',
            name='members',
            field=models.ManyToManyField(through='Machine.Stm_Tb_Model', to='Machine.tubomodel'),
        ),
        migrations.AddField(
            model_name='sistemamodel',
            name='users',
            field=models.ManyToManyField(through='Machine.User_sistemas_Model', to=settings.AUTH_USER_MODEL),
        ),
    ]
