# Generated by Django 4.1.2 on 2022-10-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_alter_historicalsistemamodel_antiguedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsistemamodel',
            name='antiguedad',
            field=models.DateField(blank=True, db_column='stm_antiguedad_sistema', null=True, verbose_name="System's year"),
        ),
        migrations.AlterField(
            model_name='historicalsistemamodel',
            name='year_instalacion',
            field=models.DateField(blank=True, db_column='stm_year_sistema', null=True, verbose_name="System's nstallation"),
        ),
        migrations.AlterField(
            model_name='historicaltubomodel',
            name='year_instalacion',
            field=models.DateField(blank=True, db_column='tb_year_componente', null=True, verbose_name="Component's installation"),
        ),
        migrations.AlterField(
            model_name='sistemamodel',
            name='antiguedad',
            field=models.DateField(blank=True, db_column='stm_antiguedad_sistema', null=True, verbose_name="System's year"),
        ),
        migrations.AlterField(
            model_name='sistemamodel',
            name='year_instalacion',
            field=models.DateField(blank=True, db_column='stm_year_sistema', null=True, verbose_name="System's nstallation"),
        ),
        migrations.AlterField(
            model_name='tubomodel',
            name='year_instalacion',
            field=models.DateField(blank=True, db_column='tb_year_componente', null=True, verbose_name="Component's installation"),
        ),
    ]
