# Generated by Django 4.1.1 on 2022-09-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Machine', '0002_alter_sistemamodel_antiguedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemamodel',
            name='antiguedad',
            field=models.DateField(blank=True, db_column='stm_antiguedad_sistema', null=True, verbose_name="System's year"),
        ),
        migrations.AlterField(
            model_name='sistemamodel',
            name='year_instalacion',
            field=models.DateField(blank=True, db_column='stm_year_sistema', null=True, verbose_name="System's nstallation"),
        ),
        migrations.AlterField(
            model_name='stm_tb_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tubomodel',
            name='antiguedad',
            field=models.DateField(blank=True, db_column='tb_antiguedad_tubo', null=True, verbose_name="Tube's year"),
        ),
        migrations.CreateModel(
            name='User_tubos_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.tubomodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_sistemas_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.sistemamodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sistemamodel',
            name='users',
            field=models.ManyToManyField(through='Machine.User_sistemas_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tubomodel',
            name='users',
            field=models.ManyToManyField(through='Machine.User_tubos_Model', to=settings.AUTH_USER_MODEL),
        ),
    ]
