# Generated by Django 4.1.5 on 2023-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_initial'),
        ('Machine', '0005_alter_historicalsistemamodel_options_and_more'),
    ]

    operations = [
    ]
