# Generated by Django 4.1.1 on 2022-09-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolsModel',
            fields=[
                ('id', models.BigAutoField(db_column='prt_id', primary_key=True, serialize=False)),
                ('protocolo_titulo', models.CharField(db_column='prt_nombre', max_length=255, unique=True, verbose_name='Protocol name')),
                ('protocolo_detalles', models.JSONField(blank=True, db_column='prt_detalles', null=True, verbose_name='Protocol details')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'protocols_Protocolos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scc_Prb_Model',
            fields=[
                ('id', models.BigAutoField(db_column='SccPrb_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebasmodel')),
            ],
            options={
                'db_table': 'protocols_secciones_prueba',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='scc_id', primary_key=True, serialize=False)),
                ('secciones_titulo', models.CharField(db_column='scc_nombre', max_length=255, unique=True, verbose_name='Section name')),
                ('secciones_contexto', models.TextField(blank=True, db_column='scc_contexto', null=True, verbose_name='Section context')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('pruebas', models.ManyToManyField(through='Protocol.Scc_Prb_Model', to='Tests.pruebasmodel')),
            ],
            options={
                'db_table': 'protocols_Secciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='scc_prb_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.CreateModel(
            name='Prt_Scc_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrtScc_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel')),
            ],
            options={
                'db_table': 'protocols_protocolo_secciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Protocol.Prt_Scc_Model', to='Protocol.seccionesmodel'),
        ),
    ]
