# Generated by Django 4.1.2 on 2022-10-26 01:31

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operations', '0008_alter_historicalvariablesmodel_nombre_variable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prb_Calculo_Operacion_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCalOpr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tests_calculo_operacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolsModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='prt_id', primary_key=True, serialize=False)),
                ('protocolo_titulo', models.CharField(db_column='prt_nombre', max_length=255, unique=True, verbose_name='Protocol name')),
            ],
            options={
                'db_table': 'protocols_Protocolos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prueba_Tipo_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCal_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaCalculoModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='prb_cal_id', primary_key=True, serialize=False)),
                ('pruebas_titulo', models.CharField(db_column='prb_cal_titulo', max_length=255, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_cal_contexto', null=True, verbose_name='Test context')),
                ('operacion', models.ManyToManyField(through='Protocol.Prb_Calculo_Operacion_Model', to='Operations.operacionesmodel')),
            ],
            options={
                'db_table': 'tests_PruebaCalculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaOpcionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='prb_opc_id', primary_key=True, serialize=False)),
                ('pruebas_titulo', models.CharField(db_column='prb_opc_titulo', max_length=255, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_opc_contexto', null=True, verbose_name='Test context')),
                ('pruebas_opciones', models.JSONField(db_column='prb_opc_resultado', verbose_name='Test results')),
            ],
            options={
                'db_table': 'tests_PruebaOpciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='scc_id', primary_key=True, serialize=False)),
                ('secciones_titulo', models.CharField(db_column='scc_nombre', max_length=255, verbose_name='Section name')),
                ('secciones_contexto', models.TextField(blank=True, db_column='scc_contexto', null=True, verbose_name='Section context')),
                ('calculo', models.ManyToManyField(through='Protocol.Prueba_Tipo_Model', to='Protocol.pruebacalculomodel')),
                ('opcion', models.ManyToManyField(through='Protocol.Prueba_Tipo_Model', to='Protocol.pruebaopcionesmodel')),
            ],
            options={
                'db_table': 'protocols_Secciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='prueba_tipo_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prueba_tipo_model',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='prueba_tipo_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.CreateModel(
            name='Prt_Scc_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrtScc_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel')),
            ],
            options={
                'db_table': 'protocols_protocolo_secciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Protocol.Prt_Scc_Model', to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_operacion_model',
            name='calculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_operacion_model',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.operacionesmodel'),
        ),
        migrations.CreateModel(
            name='HistoricalSeccionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='scc_id', db_index=True)),
                ('secciones_titulo', models.CharField(db_column='scc_nombre', max_length=255, verbose_name='Section name')),
                ('secciones_contexto', models.TextField(blank=True, db_column='scc_contexto', null=True, verbose_name='Section context')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPruebaOpcionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='prb_opc_id', db_index=True)),
                ('pruebas_titulo', models.CharField(db_column='prb_opc_titulo', max_length=255, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_opc_contexto', null=True, verbose_name='Test context')),
                ('pruebas_opciones', models.JSONField(db_column='prb_opc_resultado', verbose_name='Test results')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPruebaCalculoModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='prb_cal_id', db_index=True)),
                ('pruebas_titulo', models.CharField(db_column='prb_cal_titulo', max_length=255, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_cal_contexto', null=True, verbose_name='Test context')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProtocolsModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='prt_id', db_index=True)),
                ('protocolo_titulo', models.CharField(db_column='prt_nombre', db_index=True, max_length=255, verbose_name='Protocol name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
