# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prb_Calculo_Operacion_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCalOpr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tests_calculo_operacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prb_Operacion_Variables',
            fields=[
                ('id', models.BigAutoField(db_column='PrbOprVar_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tests_operacion_variables',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolsModel',
            fields=[
                ('id', models.BigAutoField(db_column='prt_id', primary_key=True, serialize=False)),
                ('protocolo_titulo', models.CharField(db_column='prt_nombre', max_length=255, unique=True, verbose_name='Protocol name')),
                ('protocolo_detalles', models.JSONField(db_column='prt_detalles', null=True, verbose_name='Protocol details')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'protocols_Protocolos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prt_Scc_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrtScc_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'protocols_protocolo_secciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prt_Var_Model',
            fields=[
                ('id', models.BigAutoField(db_column='Pr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'protocols_Protocolo_Variables',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prueba_Tipo_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCal_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaCalculoModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_cal_id', primary_key=True, serialize=False)),
                ('pruebas_titulo', models.CharField(db_column='prb_cal_titulo', max_length=255, unique=True, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_cal_contexto', null=True, verbose_name='Test context')),
                ('pruebas_resultado', models.TextField(blank=True, db_column='prb_cal_resultado', null=True, verbose_name='Test results')),
                ('pruebas_tolerancia', models.TextField(db_column='prb_cal_tolerancia', verbose_name="Test's tolerance")),
                ('pruebas_condicion_respuesta', models.JSONField(db_column='prb_cal_condicion_respuesta', verbose_name="Test's condition")),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_PruebaCalculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaOpcionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_opc_id', primary_key=True, serialize=False)),
                ('pruebas_titulo', models.CharField(db_column='prb_opc_titulo', max_length=255, unique=True, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_opc_contexto', null=True, verbose_name='Test context')),
                ('pruebas_opciones', models.JSONField(db_column='prb_opc_resultado', verbose_name='Test results')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_PruebaOpciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='scc_id', primary_key=True, serialize=False)),
                ('secciones_titulo', models.CharField(db_column='scc_nombre', max_length=255, unique=True, verbose_name='Section name')),
                ('secciones_contexto', models.TextField(blank=True, db_column='scc_contexto', null=True, verbose_name='Section context')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'protocols_Secciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Protocolos_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Pruebas_Calculo_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Pruebas_Opciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Secciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Variables_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariablesModel',
            fields=[
                ('id', models.BigAutoField(db_column='var_id', primary_key=True, serialize=False)),
                ('nombre_variable', models.CharField(db_column='var_nombre', max_length=255, verbose_name='Variable name')),
                ('range_variable', models.IntegerField(db_column='var_range', verbose_name='Variable range')),
                ('valor_defecto', models.IntegerField(blank=True, db_column='var_valor_defecto', null=True, verbose_name='Variable valor ')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'protocols_Variables',
                'ordering': ['id'],
            },
        ),
    ]
