# Generated by Django 3.2.6 on 2022-09-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolsmodel',
            name='detalles_protocolo',
            field=models.JSONField(blank=True, db_column='prt_detalles', null=True, verbose_name='Protocol details'),
        ),
    ]
