# Generated by Django 3.2.6 on 2022-09-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Protocol', '0001_initial'),
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionesmodel',
            name='pruebas',
            field=models.ManyToManyField(through='Protocol.Scc_Prb_Model', to='Tests.PruebasModel'),
        ),
        migrations.AddField(
            model_name='scc_prb_model',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebasmodel'),
        ),
        migrations.AddField(
            model_name='scc_prb_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='prt_scc_model',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='prt_scc_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Protocol.Prt_Scc_Model', to='Protocol.SeccionesModel'),
        ),
    ]
