# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operations', '0002_initial'),
        ('Protocol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Variables_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_variables_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.variablesmodel'),
        ),
        migrations.AddField(
            model_name='user_variables_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_secciones_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='user_secciones_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_pruebas_opciones_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='user_pruebas_opciones_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_pruebas_calculo_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='user_pruebas_calculo_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_protocolos_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='user_protocolos_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccionesmodel',
            name='calculo',
            field=models.ManyToManyField(through='Protocol.Prueba_Tipo_Model', to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='seccionesmodel',
            name='opcion',
            field=models.ManyToManyField(through='Protocol.Prueba_Tipo_Model', to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='seccionesmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Secciones_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebaopcionesmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Pruebas_Opciones_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebacalculomodel',
            name='operacion',
            field=models.ManyToManyField(through='Protocol.Prb_Calculo_Operacion_Model', to='Operations.operacionesmodel'),
        ),
        migrations.AddField(
            model_name='pruebacalculomodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Pruebas_Calculo_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prueba_tipo_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prueba_tipo_model',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='prueba_tipo_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='prt_var_model',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='prt_var_model',
            name='variables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.variablesmodel'),
        ),
        migrations.AddField(
            model_name='prt_scc_model',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='prt_scc_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Protocol.Prt_Scc_Model', to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Protocolos_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='variables',
            field=models.ManyToManyField(through='Protocol.Prt_Var_Model', to='Protocol.variablesmodel'),
        ),
        migrations.AddField(
            model_name='prb_operacion_variables',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.prb_calculo_operacion_model'),
        ),
        migrations.AddField(
            model_name='prb_operacion_variables',
            name='variables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.variablesmodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_operacion_model',
            name='calculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_operacion_model',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.operacionesmodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_operacion_model',
            name='variable',
            field=models.ManyToManyField(through='Protocol.Prb_Operacion_Variables', to='Protocol.variablesmodel'),
        ),
    ]
