# Generated by Django 4.1.1 on 2022-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebaopcionesmodel',
            name='pruebas_contexto',
            field=models.TextField(blank=True, db_column='prb_opc_contexto', null=True, verbose_name='Test context'),
        ),
    ]
