# Generated by Django 4.1.1 on 2022-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebacalculomodel',
            name='pruebas_contexto',
            field=models.TextField(blank=True, db_column='prb_cal_contexto', null=True, verbose_name='Test context'),
        ),
        migrations.AlterField(
            model_name='pruebacalculomodel',
            name='pruebas_resultado',
            field=models.TextField(blank=True, db_column='prb_cal_resultado', null=True, verbose_name='Test results'),
        ),
    ]
