# Generated by Django 4.1.1 on 2022-09-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0002_alter_protocolsmodel_protocolo_detalles_and_more'),
        ('Protocol', '0002_alter_variablesmodel_valor_defecto'),
    ]

    operations = [
    ]
