# Generated by Django 4.1.2 on 2022-10-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0002_historicalprotocolsmodel_protocolo_detalles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprotocolsmodel',
            name='protocolo_detalles',
        ),
        migrations.RemoveField(
            model_name='protocolsmodel',
            name='protocolo_detalles',
        ),
    ]
