# Generated by Django 4.1.1 on 2022-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0002_alter_pruebaopcionesmodel_pruebas_contexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionesmodel',
            name='secciones_contexto',
            field=models.TextField(blank=True, db_column='scc_contexto', null=True, verbose_name='Section context'),
        ),
    ]
