# Generated by Django 4.1.1 on 2022-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0002_alter_pruebacalculomodel_pruebas_contexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebacalculomodel',
            name='pruebas_condicion_respuesta',
            field=models.JSONField(db_column='prb_cal_condicion_respuesta', verbose_name="Test's condition"),
        ),
    ]
