# Generated by Django 4.1.1 on 2022-09-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
        ('Protocol', '0002_alter_protocolsmodel_protocolo_detalles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prb_calculo_operacion_model',
            name='calculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AlterField(
            model_name='prb_calculo_operacion_model',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.operacionesmodel'),
        ),
    ]
