# Generated by Django 4.1.1 on 2022-10-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0003_alter_seccionesmodel_secciones_contexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba_tipo_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AlterField(
            model_name='prueba_tipo_model',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
    ]
