# Generated by Django 4.1.1 on 2022-09-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0003_alter_prb_calculo_operacion_model_calculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolsmodel',
            name='protocolo_detalles',
            field=models.JSONField(blank=True, db_column='prt_detalles', null=True, verbose_name='Protocol details'),
        ),
        migrations.AlterField(
            model_name='prueba_tipo_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AlterField(
            model_name='prueba_tipo_model',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AlterField(
            model_name='pruebasmodel',
            name='pruebas_contexto',
            field=models.TextField(blank=True, db_column='prb_contexto', null=True, verbose_name='Test context'),
        ),
        migrations.AlterField(
            model_name='seccionesmodel',
            name='secciones_contexto',
            field=models.TextField(blank=True, db_column='scc_contexto', null=True, verbose_name='Section context'),
        ),
    ]
