# Generated by Django 4.1.1 on 2022-09-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0004_alter_protocolsmodel_protocolo_detalles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prb_operacionrelacion_operacion_model',
            name='operacion',
        ),
        migrations.RemoveField(
            model_name='prb_operacionrelacion_operacion_model',
            name='operacion_relacion',
        ),
        migrations.DeleteModel(
            name='Prb_Calculo_Operacion_Relacionada_Model',
        ),
        migrations.DeleteModel(
            name='Prb_OperacionRelacion_Operacion_Model',
        ),
    ]
