# Generated by Django 4.1.2 on 2022-10-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0004_alter_historicalprotocolsmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpruebacalculomodel',
            name='pruebas_resultado',
        ),
        migrations.RemoveField(
            model_name='historicalpruebacalculomodel',
            name='pruebas_tolerancia',
        ),
        migrations.RemoveField(
            model_name='pruebacalculomodel',
            name='pruebas_resultado',
        ),
        migrations.RemoveField(
            model_name='pruebacalculomodel',
            name='pruebas_tolerancia',
        ),
    ]
