# Generated by Django 4.1.2 on 2022-10-22 15:32

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0004_alter_historicalprotocolsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprotocolsmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalpruebacalculomodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalpruebaopcionesmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalseccionesmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterField(
            model_name='historicalprotocolsmodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpruebacalculomodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpruebaopcionesmodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalseccionesmodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
