# Generated by Django 4.1.1 on 2022-09-29 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Protocol', '0005_remove_prb_operacionrelacion_operacion_model_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolsmodel',
            name='protocolo_detalles',
            field=models.JSONField(db_column='prt_detalles', null=True, verbose_name='Protocol details'),
        ),
        migrations.AlterField(
            model_name='prueba_tipo_model',
            name='calculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AlterField(
            model_name='prueba_tipo_model',
            name='opcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AlterField(
            model_name='pruebasmodel',
            name='pruebas_contexto',
            field=models.TextField(db_column='prb_contexto', null=True, verbose_name='Test context'),
        ),
        migrations.AlterField(
            model_name='seccionesmodel',
            name='secciones_contexto',
            field=models.TextField(db_column='scc_contexto', null=True, verbose_name='Section context'),
        ),
        migrations.CreateModel(
            name='User_Variables_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.variablesmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Secciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Pruebas_Opciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Pruebas_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebasmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Pruebas_Calculo_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Protocolos_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='protocolsmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Protocolos_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebacalculomodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Pruebas_Calculo_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebaopcionesmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Pruebas_Opciones_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebasmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Pruebas_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccionesmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Secciones_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variablesmodel',
            name='users',
            field=models.ManyToManyField(through='Protocol.User_Variables_Model', to=settings.AUTH_USER_MODEL),
        ),
    ]
