# Generated by Django 4.1.2 on 2022-10-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0005_alter_historicalprotocolsmodel_options_and_more'),
        ('Protocol', '0006_remove_historicalpruebacalculomodel_pruebas_condicion_respuesta_and_more'),
    ]

    operations = [
    ]
