# Generated by Django 3.2.6 on 2022-09-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='InpFs_id', primary_key=True, serialize=False)),
                ('operacion_titulo', models.CharField(db_column='opr_titulo', max_length=255, unique=True, verbose_name="Operation's title")),
                ('operacion_funcion', models.CharField(db_column='opr_funcion', max_length=255, unique=True, verbose_name="Operation's function")),
                ('operacion_contexto', models.TextField(db_column='opr_contexto', max_length=255, unique=True, verbose_name="Operation's context")),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'operations_Operaciones',
                'ordering': ['id'],
            },
        ),
    ]
