# Generated by Django 4.1.1 on 2022-10-11 05:41

import User.models
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOperacionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='InpFs_id', db_index=True)),
                ('operacion_titulo', models.CharField(db_column='opr_titulo', db_index=True, max_length=255, verbose_name="Operation's title")),
                ('operacion_funcion', models.CharField(db_column='opr_funcion', db_index=True, max_length=255, verbose_name="Operation's function")),
                ('operacion_symbol', models.CharField(blank=True, db_column='opr_simbolo', db_index=True, max_length=255, null=True, verbose_name="Operation's symbol")),
                ('operacion_variable', models.IntegerField(db_column='opr_cantidad_variables', default=1, verbose_name="Operation's number of variables")),
                ('operacion_contexto', models.TextField(blank=True, db_column='opr_contexto', max_length=255, verbose_name="Operation's context")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OperacionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='InpFs_id', primary_key=True, serialize=False)),
                ('operacion_titulo', models.CharField(db_column='opr_titulo', max_length=255, unique=True, verbose_name="Operation's title")),
                ('operacion_funcion', models.CharField(db_column='opr_funcion', max_length=255, unique=True, verbose_name="Operation's function")),
                ('operacion_symbol', models.CharField(blank=True, db_column='opr_simbolo', max_length=255, null=True, unique=True, verbose_name="Operation's symbol")),
                ('operacion_variable', models.IntegerField(db_column='opr_cantidad_variables', default=1, verbose_name="Operation's number of variables")),
                ('operacion_contexto', models.TextField(blank=True, db_column='opr_contexto', max_length=255, verbose_name="Operation's context")),
            ],
            options={
                'db_table': 'operations_Operaciones',
                'ordering': ['id'],
            },
        ),
    ]
