# Generated by Django 4.0.7 on 2022-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionesfisicasmodel',
            name='inspeccion_fisica_titulo',
            field=models.CharField(db_column='InpFs_name', max_length=255, unique=True, verbose_name='Physical inspection title'),
        ),
    ]
