# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_operaciones_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacionesmodel',
            name='users',
            field=models.ManyToManyField(through='Operations.User_Operaciones_Model', to=settings.AUTH_USER_MODEL),
        ),
    ]
