# Generated by Django 4.1.2 on 2022-10-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvariablesmodel',
            name='nombre_variable',
            field=models.CharField(db_column='var_nombre', db_index=True, max_length=255, verbose_name='Variable name'),
        ),
        migrations.AlterField(
            model_name='variablesmodel',
            name='nombre_variable',
            field=models.CharField(db_column='var_nombre', max_length=255, unique=True, verbose_name='Variable name'),
        ),
    ]
