# Generated by Django 4.1.1 on 2022-09-29 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesmodel',
            name='operacion_contexto',
            field=models.TextField(blank=True, db_column='opr_contexto', max_length=255, verbose_name="Operation's context"),
        ),
        migrations.CreateModel(
            name='User_Operaciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operations.operacionesmodel')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operacionesmodel',
            name='users',
            field=models.ManyToManyField(through='Operations.User_Operaciones_Model', to=settings.AUTH_USER_MODEL),
        ),
    ]
