# Generated by Django 4.1.2 on 2022-10-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_alter_historicalvariablesmodel_valor_defecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvariablesmodel',
            name='valor_defecto',
            field=models.JSONField(db_column='var_valor_defecto', null=True, verbose_name='Variable valor '),
        ),
        migrations.AlterField(
            model_name='variablesmodel',
            name='valor_defecto',
            field=models.JSONField(db_column='var_valor_defecto', null=True, verbose_name='Variable valor '),
        ),
    ]
