# Generated by Django 4.1.1 on 2022-10-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_alter_operacionesmodel_operacion_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesmodel',
            name='operacion_symbol',
            field=models.CharField(blank=True, db_column='opr_simbolo', max_length=255, null=True, unique=True, verbose_name="Operation's symbol"),
        ),
    ]
