# Generated by Django 4.1.1 on 2022-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0003_alter_operacionesmodel_operacion_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionesmodel',
            name='operacion_variable',
            field=models.IntegerField(blank=True, db_column='opr_cantidad_variables', default=1, null=True, verbose_name="Operation's number of variables"),
        ),
    ]
