# Generated by Django 4.1.2 on 2022-10-22 04:57

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0003_alter_historicalvariablesmodel_valor_defecto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcategoryoperacionesmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User, 'verbose_name_plural': 'historical category operaciones models'},
        ),
        migrations.AlterModelOptions(
            name='historicaloperacionesmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User, 'verbose_name_plural': 'historical operaciones models'},
        ),
        migrations.AlterModelOptions(
            name='historicalvariablesmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User, 'verbose_name_plural': 'historical variables models'},
        ),
        migrations.AlterField(
            model_name='historicalcategoryoperacionesmodel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaloperacionesmodel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvariablesmodel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
