# Generated by Django 4.1.1 on 2022-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0004_operacionesmodel_operacion_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesmodel',
            name='operacion_variable',
            field=models.IntegerField(db_column='opr_cantidad_variables', default=1, verbose_name="Operation's number of variables"),
        ),
    ]
