# Generated by Django 4.1.2 on 2022-10-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0005_alter_historicalcategoryoperacionesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvariablesmodel',
            name='valor_defecto',
            field=models.JSONField(blank=True, db_column='var_valor_defecto', null=True, verbose_name='Variable valor '),
        ),
        migrations.AlterField(
            model_name='variablesmodel',
            name='valor_defecto',
            field=models.JSONField(blank=True, db_column='var_valor_defecto', null=True, verbose_name='Variable valor '),
        ),
    ]
