# Generated by Django 4.1.2 on 2022-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0006_alter_historicalvariablesmodel_valor_defecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacionesmodel',
            name='operacion_titulo',
            field=models.CharField(db_column='opr_titulo', max_length=255, verbose_name="Operation's title"),
        ),
        migrations.AlterField(
            model_name='operacionesmodel',
            name='operacion_titulo',
            field=models.CharField(db_column='opr_titulo', max_length=255, verbose_name="Operation's title"),
        ),
    ]
