# Generated by Django 4.1.2 on 2022-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0007_alter_historicaloperacionesmodel_operacion_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvariablesmodel',
            name='nombre_variable',
            field=models.CharField(db_column='var_nombre', max_length=255, verbose_name='Variable name'),
        ),
        migrations.AlterField(
            model_name='variablesmodel',
            name='nombre_variable',
            field=models.CharField(db_column='var_nombre', max_length=255, verbose_name='Variable name'),
        ),
    ]
