# Generated by Django 4.1.5 on 2023-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_initial'),
        ('Operations', '0008_alter_historicalvariablesmodel_nombre_variable_and_more'),
    ]

    operations = [
    ]
