# Generated by Django 4.1.1 on 2022-09-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('CompanyMachine', '0001_initial'),
        ('Tests', '0001_initial'),
        ('Protocol', '0001_initial'),
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frt_Cat_Model',
            fields=[
                ('id', models.BigAutoField(db_column='FrtCat_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'reports_formatos_categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportsFormatsModel',
            fields=[
                ('id', models.BigAutoField(db_column='rep_frt_id', primary_key=True, serialize=False)),
                ('codigo_formato', models.CharField(blank=True, db_column='rep_frt_codigo', max_length=255, null=True, unique=True, verbose_name='Format code')),
                ('nombre_formato', models.CharField(db_column='rep_frt_nombre', max_length=255, verbose_name='Format name')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'reports_Formatos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportsReporteModel',
            fields=[
                ('id', models.BigAutoField(db_column='rpt_id', primary_key=True, serialize=False)),
                ('fecha_control_calidad', models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'reports_Reportes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Tb_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptTb_id', primary_key=True, serialize=False)),
                ('context_json', models.JSONField(db_column='RptTb_context', verbose_name="Tube's context")),
                ('crated_at', models.DateTimeField(editable=False)),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
                ('tubo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.tubomodel')),
            ],
            options={
                'db_table': 'reports_rpt_Tb',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Prt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrt_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Prt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Prb_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrb_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebasmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_prb_Med',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Med_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptMed_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Med',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Frt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('formatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Frt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Ar_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('cliente_static_details', models.JSONField(db_column='RptAr_context', verbose_name="Customer's current details")),
                ('crated_at', models.DateTimeField(editable=False)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.areasmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_ar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='cliente',
            field=models.ManyToManyField(through='Reports.Rpt_Ar_Model', to='Customer.areasmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='formato',
            field=models.ManyToManyField(through='Reports.Rpt_Frt_Model', to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='machine',
            field=models.ManyToManyField(through='Reports.Rpt_Med_Model', to='CompanyMachine.medidoresmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='protocolo',
            field=models.ManyToManyField(through='Reports.Rpt_Prt_Model', to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='pruebas',
            field=models.ManyToManyField(through='Reports.Rpt_Prb_Model', to='Tests.pruebasmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='tubo',
            field=models.ManyToManyField(through='Reports.Rpt_Tb_Model', to='Machine.tubomodel'),
        ),
        migrations.CreateModel(
            name='ReportsCategoryModel',
            fields=[
                ('id', models.BigAutoField(db_column='rep_cat_id', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='rep_cat_area', max_length=255, verbose_name='Category name')),
                ('abreviatura_categoria', models.CharField(blank=True, db_column='rep_cat_abreviatura', max_length=255, null=True, unique=True, verbose_name='Category abbreviation')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('members', models.ManyToManyField(through='Reports.Frt_Cat_Model', to='Reports.reportsformatsmodel')),
            ],
            options={
                'db_table': 'reports_Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='frt_cat_model',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportscategorymodel'),
        ),
        migrations.AddField(
            model_name='frt_cat_model',
            name='formatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
    ]
