# Generated by Django 4.1.1 on 2022-10-11 05:41

import User.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Protocol', '0001_initial'),
        ('Customer', '0001_initial'),
        ('CompanyMachine', '0001_initial'),
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frt_Cat_Model',
            fields=[
                ('id', models.BigAutoField(db_column='FrtCat_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'reports_formatos_categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReportsCategoryModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rep_cat_id', db_index=True)),
                ('nombre_categoria', models.CharField(db_column='rep_cat_area', max_length=255, verbose_name='Category name')),
                ('abreviatura_categoria', models.CharField(db_column='rep_cat_abreviatura', db_index=True, max_length=255, verbose_name='Category abbreviation')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReportsFormatsModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rep_frt_id', db_index=True)),
                ('codigo_formato', models.CharField(blank=True, db_column='rep_frt_codigo', db_index=True, max_length=255, null=True, verbose_name='Format code')),
                ('nombre_formato', models.CharField(blank=True, db_column='rep_frt_nombre', max_length=255, verbose_name='Format name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReportsReporteModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rpt_id', db_index=True)),
                ('fecha_control_calidad', models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date')),
                ('numero_de_ot', models.CharField(db_column='rpt_numero_orden_trabajo', max_length=255, verbose_name='Ot number')),
                ('valores_operaciones', models.JSONField(db_column='rpt_valores_operaciones', verbose_name='Values for operations')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReportsFormatsModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rep_frt_id', primary_key=True, serialize=False)),
                ('codigo_formato', models.CharField(blank=True, db_column='rep_frt_codigo', max_length=255, null=True, unique=True, verbose_name='Format code')),
                ('nombre_formato', models.CharField(blank=True, db_column='rep_frt_nombre', max_length=255, verbose_name='Format name')),
            ],
            options={
                'db_table': 'reports_Formatos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportsReporteModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rpt_id', primary_key=True, serialize=False)),
                ('fecha_control_calidad', models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date')),
                ('numero_de_ot', models.CharField(db_column='rpt_numero_orden_trabajo', max_length=255, verbose_name='Ot number')),
                ('valores_operaciones', models.JSONField(db_column='rpt_valores_operaciones', verbose_name='Values for operations')),
            ],
            options={
                'db_table': 'reports_Reportes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Tb_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptTb_id', primary_key=True, serialize=False)),
                ('tubo_context_json', models.JSONField(db_column='RptTb_context', verbose_name="Tube's context")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
                ('tubo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.tubomodel')),
            ],
            options={
                'db_table': 'reports_rpt_Tb',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Stm_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptStm_id', primary_key=True, serialize=False)),
                ('sistema_context_json', models.JSONField(db_column='RptStm_context', verbose_name="System's context")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.sistemamodel')),
            ],
            options={
                'db_table': 'reports_rpt_Stm',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Secc_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptSecc_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel')),
            ],
            options={
                'db_table': 'reports_rpt_secc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Prt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrt_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
            ],
            options={
                'db_table': 'reports_rpt_Prt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Prb_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrb_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel')),
            ],
            options={
                'db_table': 'reports_rpt_prb',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_org_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organizaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.organizacionmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_org',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Med_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptMed_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Med',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Frt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Frt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_dpt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.departamentomodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_dpt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Ar_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.areasmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_ar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='area',
            field=models.ManyToManyField(through='Reports.Rpt_Ar_Model', to='Customer.areasmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='departamentos',
            field=models.ManyToManyField(through='Reports.Rpt_dpt_Model', to='Customer.departamentomodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='formato',
            field=models.ManyToManyField(through='Reports.Rpt_Frt_Model', to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='machine',
            field=models.ManyToManyField(through='Reports.Rpt_Med_Model', to='CompanyMachine.medidoresmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='organizacion',
            field=models.ManyToManyField(through='Reports.Rpt_org_Model', to='Customer.organizacionmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='sistema',
            field=models.ManyToManyField(through='Reports.Rpt_Stm_Model', to='Machine.sistemamodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='tubo',
            field=models.ManyToManyField(through='Reports.Rpt_Tb_Model', to='Machine.tubomodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='calculo',
            field=models.ManyToManyField(through='Reports.Rpt_Prb_Model', to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='opcion',
            field=models.ManyToManyField(through='Reports.Rpt_Prb_Model', to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='protocolo',
            field=models.ManyToManyField(through='Reports.Rpt_Prt_Model', to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Reports.Rpt_Secc_Model', to='Protocol.seccionesmodel'),
        ),
        migrations.CreateModel(
            name='ReportsCategoryModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rep_cat_id', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='rep_cat_area', max_length=255, verbose_name='Category name')),
                ('abreviatura_categoria', models.CharField(db_column='rep_cat_abreviatura', max_length=255, unique=True, verbose_name='Category abbreviation')),
                ('members', models.ManyToManyField(through='Reports.Frt_Cat_Model', to='Reports.reportsformatsmodel')),
            ],
            options={
                'db_table': 'reports_Categorias',
                'ordering': ['id'],
            },
        ),
    ]
