# Generated by Django 4.1.5 on 2023-01-21 17:38

import User.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operations', '0001_initial'),
        ('Protocol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frt_Cat_Model',
            fields=[
                ('id', models.BigAutoField(db_column='FrtCat_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'reports_formatos_categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReportsCategoryModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rep_cat_id', db_index=True)),
                ('nombre_categoria', models.CharField(db_column='rep_cat_area', max_length=255, verbose_name='Category name')),
                ('abreviatura_categoria', models.CharField(db_column='rep_cat_abreviatura', db_index=True, max_length=255, verbose_name='Category abbreviation')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReportsCertificadoModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rpi_id', db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReportsFormatsModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rep_frt_id', db_index=True)),
                ('codigo_formato', models.CharField(blank=True, db_column='rep_frt_codigo', db_index=True, max_length=255, null=True, verbose_name='Format code')),
                ('nombre_formato', models.CharField(blank=True, db_column='rep_frt_nombre', max_length=255, verbose_name='Format name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReportsCertificadoModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rpi_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reports_Certificado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportsFormatsModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rep_frt_id', primary_key=True, serialize=False)),
                ('codigo_formato', models.CharField(blank=True, db_column='rep_frt_codigo', max_length=255, null=True, unique=True, verbose_name='Format code')),
                ('nombre_formato', models.CharField(blank=True, db_column='rep_frt_nombre', max_length=255, verbose_name='Format name')),
            ],
            options={
                'db_table': 'reports_Formatos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportsReporteModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rpt_id', primary_key=True, serialize=False)),
                ('nombre_reporte', models.CharField(blank=True, db_column='rpt_name_reporte', max_length=255, null=True, verbose_name='Report name')),
                ('numero_de_ot', models.CharField(blank=True, db_column='rpt_numero_orden_trabajo', max_length=255, null=True, verbose_name='Ot number')),
                ('fecha_control_calidad', models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date')),
                ('observacion', models.TextField(blank=True, db_column='rpt_observacion_reporte', null=True, verbose_name='Report observacion')),
                ('datos_del_cliente', models.JSONField(blank=True, db_column='rpt_data_clientes', null=True, verbose_name='Data for clients')),
                ('sistema', models.JSONField(blank=True, db_column='rpt_data_sistema', null=True, verbose_name='Data for system')),
                ('componente', models.JSONField(blank=True, db_column='rpt_data_component', null=True, verbose_name='Data for component')),
                ('machine', models.JSONField(blank=True, db_column='rpt_data_maquina', null=True, verbose_name='Values for machine')),
                ('valores_operaciones', models.JSONField(blank=True, db_column='rpt_valores_operaciones', null=True, verbose_name='Values for operations')),
                ('pruebas', models.JSONField(blank=True, db_column='rpt_pruebas', null=True, verbose_name='Values for Pruebas')),
                ('title_image_1', models.CharField(db_column='rpt_title_image_1', max_length=255, null=True, verbose_name='Title image 1')),
                ('image_1', models.ImageField(blank='', default='', upload_to='reports/')),
                ('title_image_2', models.CharField(db_column='rpt_title_image_2', max_length=255, null=True, verbose_name='Title image 2')),
                ('image_2', models.ImageField(blank='', default='', upload_to='reports/')),
                ('title_image_3', models.CharField(db_column='rpt_title_image_3', max_length=255, null=True, verbose_name='Title image 3')),
                ('image_3', models.ImageField(blank='', default='', null=True, upload_to='reports/')),
                ('certificado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.reportscertificadomodel')),
            ],
            options={
                'db_table': 'reports_Reportes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Varr_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptVar_id', primary_key=True, serialize=False)),
                ('subtitle_posicion', models.TextField(blank=True, db_column='rpt_varr_seccion_title', null=True, verbose_name='Title Seccion')),
                ('posicion', models.IntegerField(db_column='rpt_varr_posicion', verbose_name='Contenedor de Variable en reporte')),
                ('sub_posicion', models.IntegerField(db_column='rpt_varr_sub_posicion', verbose_name='Posicion de variable en contenedor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.variablesmodel')),
            ],
            options={
                'db_table': 'reports_formatos_variables',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Secc_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptSecc_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel')),
            ],
            options={
                'db_table': 'reports_rpt_secc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Prt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrt_id', primary_key=True, serialize=False)),
                ('protocolo_detalles', models.JSONField(db_column='RptPrt_detalles', null=True, verbose_name='Protocol details')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
            ],
            options={
                'db_table': 'reports_rpt_Prt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Frt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptAr_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Frt',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='formato',
            field=models.ManyToManyField(through='Reports.Rpt_Frt_Model', to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='protocolo',
            field=models.ManyToManyField(through='Reports.Rpt_Prt_Model', to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Reports.Rpt_Secc_Model', to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='variables_formato',
            field=models.ManyToManyField(through='Reports.Rpt_Varr_Model', to='Operations.variablesmodel'),
        ),
        migrations.CreateModel(
            name='ReportsCategoryModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='rep_cat_id', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='rep_cat_area', max_length=255, verbose_name='Category name')),
                ('abreviatura_categoria', models.CharField(db_column='rep_cat_abreviatura', max_length=255, unique=True, verbose_name='Category abbreviation')),
                ('members', models.ManyToManyField(through='Reports.Frt_Cat_Model', to='Reports.reportsformatsmodel')),
            ],
            options={
                'db_table': 'reports_Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReportsReporteModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='rpt_id', db_index=True)),
                ('nombre_reporte', models.CharField(blank=True, db_column='rpt_name_reporte', max_length=255, null=True, verbose_name='Report name')),
                ('numero_de_ot', models.CharField(blank=True, db_column='rpt_numero_orden_trabajo', max_length=255, null=True, verbose_name='Ot number')),
                ('fecha_control_calidad', models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date')),
                ('observacion', models.TextField(blank=True, db_column='rpt_observacion_reporte', null=True, verbose_name='Report observacion')),
                ('datos_del_cliente', models.JSONField(blank=True, db_column='rpt_data_clientes', null=True, verbose_name='Data for clients')),
                ('sistema', models.JSONField(blank=True, db_column='rpt_data_sistema', null=True, verbose_name='Data for system')),
                ('componente', models.JSONField(blank=True, db_column='rpt_data_component', null=True, verbose_name='Data for component')),
                ('machine', models.JSONField(blank=True, db_column='rpt_data_maquina', null=True, verbose_name='Values for machine')),
                ('valores_operaciones', models.JSONField(blank=True, db_column='rpt_valores_operaciones', null=True, verbose_name='Values for operations')),
                ('pruebas', models.JSONField(blank=True, db_column='rpt_pruebas', null=True, verbose_name='Values for Pruebas')),
                ('title_image_1', models.CharField(db_column='rpt_title_image_1', max_length=255, null=True, verbose_name='Title image 1')),
                ('image_1', models.TextField(blank='', default='', max_length=100)),
                ('title_image_2', models.CharField(db_column='rpt_title_image_2', max_length=255, null=True, verbose_name='Title image 2')),
                ('image_2', models.TextField(blank='', default='', max_length=100)),
                ('title_image_3', models.CharField(db_column='rpt_title_image_3', max_length=255, null=True, verbose_name='Title image 3')),
                ('image_3', models.TextField(blank='', default='', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('certificado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Reports.reportscertificadomodel')),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
