# Generated by Django 4.1.2 on 2022-10-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsformatsmodel',
            name='calculo',
        ),
        migrations.RemoveField(
            model_name='reportsformatsmodel',
            name='opcion',
        ),
        migrations.DeleteModel(
            name='Rpt_Prb_Model',
        ),
    ]
