# Generated by Django 3.2.6 on 2022-09-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0001_initial'),
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpt_Prb_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrb_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebasmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_prb_Med',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='pruebas',
            field=models.ManyToManyField(through='Reports.Rpt_Prb_Model', to='Tests.PruebasModel'),
        ),
    ]
