# Generated by Django 4.1.5 on 2023-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='fecha_control_calidad',
            field=models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='fecha_control_calidad',
            field=models.DateField(db_column='rpt_fecha_control_calidad', verbose_name='QC date'),
        ),
    ]
