# Generated by Django 4.1.1 on 2022-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportscategorymodel',
            name='abreviatura_categoria',
            field=models.CharField(db_column='rep_cat_abreviatura', max_length=255, null=True, unique=True, verbose_name='Category abbreviation'),
        ),
        migrations.AlterField(
            model_name='reportsformatsmodel',
            name='codigo_formato',
            field=models.CharField(db_column='rep_frt_codigo', max_length=255, null=True, unique=True, verbose_name='Format code'),
        ),
        migrations.AlterField(
            model_name='rpt_ar_model',
            name='cliente_static_details',
            field=models.JSONField(db_column='RptAr_context', null=True, verbose_name="Customer's current details"),
        ),
    ]
