# Generated by Django 4.1.2 on 2022-10-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportsreportemodel',
            name='preubas',
            field=models.JSONField(blank=True, db_column='rpt_pruebas', null=True, verbose_name='Values for Pruebas'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='preubas',
            field=models.JSONField(blank=True, db_column='rpt_pruebas', null=True, verbose_name='Values for Pruebas'),
        ),
    ]
