# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Protocol', '0002_initial'),
        ('Customer', '0002_initial'),
        ('CompanyMachine', '0002_initial'),
        ('Reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Machine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reportes_reportes_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_reportes_formatos_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='user_reportes_formatos_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_reportes_categoria_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportscategorymodel'),
        ),
        migrations.AddField(
            model_name='user_reportes_categoria_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rpt_tb_model',
            name='reportes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='rpt_tb_model',
            name='tubo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.tubomodel'),
        ),
        migrations.AddField(
            model_name='rpt_stm_model',
            name='reportes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='rpt_stm_model',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.sistemamodel'),
        ),
        migrations.AddField(
            model_name='rpt_secc_model',
            name='formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='rpt_secc_model',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='rpt_prt_model',
            name='formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='rpt_prt_model',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='rpt_prb_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='rpt_prb_model',
            name='formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='rpt_prb_model',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='rpt_org_model',
            name='organizaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.organizacionmodel'),
        ),
        migrations.AddField(
            model_name='rpt_org_model',
            name='reportes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='rpt_med_model',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel'),
        ),
        migrations.AddField(
            model_name='rpt_med_model',
            name='reportes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='rpt_frt_model',
            name='formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='rpt_frt_model',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='rpt_dpt_model',
            name='departamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.departamentomodel'),
        ),
        migrations.AddField(
            model_name='rpt_dpt_model',
            name='reportes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='rpt_ar_model',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.areasmodel'),
        ),
        migrations.AddField(
            model_name='rpt_ar_model',
            name='reportes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='area',
            field=models.ManyToManyField(through='Reports.Rpt_Ar_Model', to='Customer.areasmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='departamentos',
            field=models.ManyToManyField(through='Reports.Rpt_dpt_Model', to='Customer.departamentomodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='formato',
            field=models.ManyToManyField(through='Reports.Rpt_Frt_Model', to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='machine',
            field=models.ManyToManyField(through='Reports.Rpt_Med_Model', to='CompanyMachine.medidoresmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='organizacion',
            field=models.ManyToManyField(through='Reports.Rpt_org_Model', to='Customer.organizacionmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='sistema',
            field=models.ManyToManyField(through='Reports.Rpt_Stm_Model', to='Machine.sistemamodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='tubo',
            field=models.ManyToManyField(through='Reports.Rpt_Tb_Model', to='Machine.tubomodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='calculo',
            field=models.ManyToManyField(through='Reports.Rpt_Prb_Model', to='Protocol.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='opcion',
            field=models.ManyToManyField(through='Reports.Rpt_Prb_Model', to='Protocol.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='protocolo',
            field=models.ManyToManyField(through='Reports.Rpt_Prt_Model', to='Protocol.protocolsmodel'),
        ),
        migrations.AddField(
            model_name='reportsformatsmodel',
            name='secciones',
            field=models.ManyToManyField(through='Reports.Rpt_Secc_Model', to='Protocol.seccionesmodel'),
        ),
        migrations.AddField(
            model_name='reportscategorymodel',
            name='members',
            field=models.ManyToManyField(through='Reports.Frt_Cat_Model', to='Reports.reportsformatsmodel'),
        ),
        migrations.AddField(
            model_name='frt_cat_model',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportscategorymodel'),
        ),
        migrations.AddField(
            model_name='frt_cat_model',
            name='formatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
    ]
