# Generated by Django 4.1.1 on 2022-09-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMachine', '0001_initial'),
        ('Protocol', '0002_protocolsmodel_detalles_protocolo'),
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpt_Prt_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptPrt_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocol.protocolsmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Prt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpt_Med_Model',
            fields=[
                ('id', models.BigAutoField(db_column='RptMed_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel')),
                ('reportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsreportemodel')),
            ],
            options={
                'db_table': 'reports_rpt_Med',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='machine',
            field=models.ManyToManyField(through='Reports.Rpt_Med_Model', to='CompanyMachine.medidoresmodel'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='protocolo',
            field=models.ManyToManyField(through='Reports.Rpt_Prt_Model', to='Protocol.protocolsmodel'),
        ),
    ]
