# Generated by Django 4.1.2 on 2022-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_alter_rpt_varr_model_posicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_varr_model',
            name='posicion',
            field=models.IntegerField(blank=True, db_column='rpt_varr_posicion', default=1, null=True, verbose_name='Contenedor de Variable en reporte'),
        ),
        migrations.AlterField(
            model_name='rpt_varr_model',
            name='sub_posicion',
            field=models.IntegerField(blank=True, db_column='rpt_varr_sub_posicion', default=1, null=True, verbose_name='Posicion de variable en contenedor'),
        ),
    ]
