# Generated by Django 4.1.2 on 2022-10-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_rename_preubas_historicalreportsreportemodel_pruebas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='componente',
            field=models.JSONField(blank=True, db_column='rpt_data_component', null=True, verbose_name='Data for component'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='datos_del_cliente',
            field=models.JSONField(blank=True, db_column='rpt_data_clientes', null=True, verbose_name='Data for clients'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='machine',
            field=models.JSONField(blank=True, db_column='rpt_data_maquina', null=True, verbose_name='Values for machine'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='nombre_reporte',
            field=models.CharField(blank=True, db_column='rpt_name_reporte', max_length=255, null=True, verbose_name='Report name'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='numero_de_ot',
            field=models.CharField(blank=True, db_column='rpt_numero_orden_trabajo', max_length=255, null=True, verbose_name='Ot number'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='observacion',
            field=models.TextField(blank=True, db_column='rpt_observacion_reporte', null=True, verbose_name='Report observacion'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='sistema',
            field=models.JSONField(blank=True, db_column='rpt_data_sistema', null=True, verbose_name='Data for system'),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='valores_operaciones',
            field=models.JSONField(blank=True, db_column='rpt_valores_operaciones', null=True, verbose_name='Values for operations'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='componente',
            field=models.JSONField(blank=True, db_column='rpt_data_component', null=True, verbose_name='Data for component'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='datos_del_cliente',
            field=models.JSONField(blank=True, db_column='rpt_data_clientes', null=True, verbose_name='Data for clients'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='machine',
            field=models.JSONField(blank=True, db_column='rpt_data_maquina', null=True, verbose_name='Values for machine'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='nombre_reporte',
            field=models.CharField(blank=True, db_column='rpt_name_reporte', max_length=255, null=True, verbose_name='Report name'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='numero_de_ot',
            field=models.CharField(blank=True, db_column='rpt_numero_orden_trabajo', max_length=255, null=True, verbose_name='Ot number'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='observacion',
            field=models.TextField(blank=True, db_column='rpt_observacion_reporte', null=True, verbose_name='Report observacion'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='sistema',
            field=models.JSONField(blank=True, db_column='rpt_data_sistema', null=True, verbose_name='Data for system'),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='valores_operaciones',
            field=models.JSONField(blank=True, db_column='rpt_valores_operaciones', null=True, verbose_name='Values for operations'),
        ),
    ]
