# Generated by Django 4.1.5 on 2023-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_initial'),
        ('Reports', '0004_alter_historicalreportsreportemodel_image_3_and_more'),
    ]

    operations = [
    ]
