# Generated by Django 4.1.5 on 2023-01-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_merge_20230124_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='image_3',
            field=models.TextField(blank='', default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='image_3',
            field=models.ImageField(blank='', default='', null=True, upload_to='reports/'),
        ),
    ]
