# Generated by Django 4.1.4 on 2022-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_historicalreportsreportemodel_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportsreportemodel',
            name='title_image_1',
            field=models.CharField(db_column='rpt_title_image_1', max_length=255, null=True, verbose_name='Title image 1'),
        ),
        migrations.AddField(
            model_name='historicalreportsreportemodel',
            name='title_image_2',
            field=models.CharField(db_column='rpt_title_image_2', max_length=255, null=True, verbose_name='Title image 2'),
        ),
        migrations.AddField(
            model_name='historicalreportsreportemodel',
            name='title_image_3',
            field=models.CharField(db_column='rpt_title_image_3', max_length=255, null=True, verbose_name='Title image 3'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='title_image_1',
            field=models.CharField(db_column='rpt_title_image_1', max_length=255, null=True, verbose_name='Title image 1'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='title_image_2',
            field=models.CharField(db_column='rpt_title_image_2', max_length=255, null=True, verbose_name='Title image 2'),
        ),
        migrations.AddField(
            model_name='reportsreportemodel',
            name='title_image_3',
            field=models.CharField(db_column='rpt_title_image_3', max_length=255, null=True, verbose_name='Title image 3'),
        ),
    ]
