# Generated by Django 4.1.2 on 2022-10-22 15:32

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0006_alter_historicalreportscategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreportscategorymodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalreportsformatsmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterModelOptions(
            name='historicalreportsreportemodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': User.models.User},
        ),
        migrations.AlterField(
            model_name='historicalreportscategorymodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalreportsformatsmodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalreportsreportemodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
