# Generated by Django 4.1.4 on 2022-12-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_reportsinformesmodel_historicalreportsinformesmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsinformesmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='reportsinformesmodel',
            table='reports_Informes',
        ),
    ]
