# Generated by Django 4.1.2 on 2022-10-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_alter_historicalreportscategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_varr_model',
            name='nombre_categoria',
            field=models.IntegerField(blank=True, db_column='rpt_varr_categoria', null=True, verbose_name='Categoría de Variable'),
        ),
    ]
