# Generated by Django 4.1.2 on 2022-10-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0008_rpt_varr_model_nombre_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_varr_model',
            name='nombre_categoria',
            field=models.TextField(blank=True, db_column='rpt_varr_categoria', null=True, verbose_name='Categoría de Variable'),
        ),
    ]
