# Generated by Django 4.1.4 on 2022-12-21 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reports', '0008_alter_reportsinformesmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalReportsInformesModel',
            new_name='HistoricalReportsCertificadoModel',
        ),
        migrations.RenameModel(
            old_name='ReportsInformesModel',
            new_name='ReportsCertificadoModel',
        ),
        migrations.AlterModelTable(
            name='reportscertificadomodel',
            table='reports_Certificado',
        ),
    ]
