# Generated by Django 4.1.2 on 2022-10-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Protocol', '0007_merge_20221023_0018'),
        ('Reports', '0009_alter_rpt_varr_model_nombre_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_varr_model',
            name='nombre_categoria',
        ),
        migrations.AddField(
            model_name='rpt_varr_model',
            name='seccion',
            field=models.ForeignKey(blank=True, db_column='rpt_varr_seccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='Protocol.seccionesmodel'),
        ),
    ]
