# Generated by Django 4.1.4 on 2022-12-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0009_rename_historicalreportsinformesmodel_historicalreportscertificadomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='certificado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.reportscertificadomodel', unique=True),
        ),
    ]
