# Generated by Django 4.1.2 on 2022-10-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0010_remove_rpt_varr_model_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_varr_model',
            name='seccion',
        ),
        migrations.AddField(
            model_name='rpt_varr_model',
            name='subtitle_posicion',
            field=models.TextField(blank=True, db_column='rpt_varr_seccion_title', null=True, verbose_name='Title Seccion'),
        ),
    ]
