# Generated by Django 4.1.4 on 2022-12-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0010_alter_reportsreportemodel_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsreportemodel',
            name='certificado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.reportscertificadomodel'),
        ),
    ]
