# Generated by Django 4.1.2 on 2022-10-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0008_alter_historicalvariablesmodel_nombre_variable_and_more'),
        ('Reports', '0011_remove_rpt_varr_model_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_varr_model',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.reportsformatsmodel'),
        ),
        migrations.AlterField(
            model_name='rpt_varr_model',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.variablesmodel'),
        ),
    ]
