# Generated by Django 3.2.6 on 2022-09-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prb_Cal_Opr_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCalOpr_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_calculo_operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prb_Calculo_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCal_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_calculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prb_PrbRelacion_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbPrbRl_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_prueba_calculo_relacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaCalculo',
            fields=[
                ('id', models.BigAutoField(db_column='prb_cal_id', primary_key=True, serialize=False)),
                ('variable', models.JSONField(db_column='prb_cal_variable', verbose_name='Test variable')),
                ('pruebas_resultado', models.JSONField(db_column='prb_cal_resultado', verbose_name='Test results')),
                ('pruebas_tolerancia', models.TextField(db_column='prb_cal_tolerancia', verbose_name="Test's tolerance")),
                ('pruebas_condicion_respuesta', models.TextField(db_column='prb_cal_condicion_respuesta', verbose_name="Test's condition")),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('operaciones', models.ManyToManyField(through='Tests.Prb_Cal_Opr_Model', to='Operations.OperacionesModel')),
            ],
            options={
                'db_table': 'tests_PruebaCalculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaCalculoRelacion',
            fields=[
                ('id', models.BigAutoField(db_column='prb_cal_rel_id', primary_key=True, serialize=False)),
                ('variable', models.JSONField(db_column='prb_cal_rel_variable', verbose_name='Test variable')),
                ('pruebas_resultado', models.JSONField(db_column='prb_cal_rel_resultado', verbose_name='Test results')),
                ('pruebas_tolerancia', models.TextField(db_column='prb_cal_rel_tolerancia', verbose_name="Test's tolerance")),
                ('pruebas_condicion_respuesta', models.TextField(db_column='prb_cal_rel_condicion_respuesta', verbose_name="Test's condition")),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('operaciones', models.ManyToManyField(through='Tests.Prb_Cal_Opr_Model', to='Operations.OperacionesModel')),
            ],
            options={
                'db_table': 'tests_PruebaCalculoRelacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaOpciones',
            fields=[
                ('id', models.BigAutoField(db_column='prb_opc_id', primary_key=True, serialize=False)),
                ('pruebas_opciones', models.JSONField(db_column='prb_opc_resultado', verbose_name='Test results')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_PruebaOpciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebasModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_id', primary_key=True, serialize=False)),
                ('pruebas_titulo', models.CharField(db_column='prb_titulo', max_length=255, unique=True, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_contexto', null=True, verbose_name='Test context')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('calculo', models.ManyToManyField(through='Tests.Prb_Calculo_Model', to='Tests.PruebaCalculo')),
                ('calculo_relacion', models.ManyToManyField(through='Tests.Prb_Calculo_Model', to='Tests.PruebaCalculoRelacion')),
                ('opcion', models.ManyToManyField(through='Tests.Prb_Calculo_Model', to='Tests.PruebaOpciones')),
            ],
            options={
                'db_table': 'tests_Pruebas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pruebacalculo',
            name='prueba_relacion',
            field=models.ManyToManyField(through='Tests.Prb_PrbRelacion_Model', to='Tests.PruebaCalculoRelacion'),
        ),
        migrations.AddField(
            model_name='prb_prbrelacion_model',
            name='prueba_calculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculo'),
        ),
        migrations.AddField(
            model_name='prb_prbrelacion_model',
            name='prueba_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculorelacion'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='calculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculo'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='calculo_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculorelacion'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebaopciones'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebasmodel'),
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='calculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculo'),
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='calculo_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculorelacion'),
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operations.operacionesmodel'),
        ),
    ]
