# Generated by Django 4.1.1 on 2022-09-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prb_Cal_Opr_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCalOpr_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_calculo_operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prb_Calculo_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCal_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_calculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prb_PrbRelacion_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbPrbRl_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_prueba_prueba_calculo_relacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaCalculoModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_cal_id', primary_key=True, serialize=False)),
                ('pruebas_resultado', models.JSONField(db_column='prb_cal_resultado', verbose_name='Test results')),
                ('pruebas_tolerancia', models.TextField(db_column='prb_cal_tolerancia', verbose_name="Test's tolerance")),
                ('pruebas_condicion_respuesta', models.TextField(db_column='prb_cal_condicion_respuesta', verbose_name="Test's condition")),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('operacion', models.ManyToManyField(through='Tests.Prb_Cal_Opr_Model', to='Operations.operacionesmodel')),
            ],
            options={
                'db_table': 'tests_PruebaCalculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaCalculoRelacionModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_cal_rel_id', primary_key=True, serialize=False)),
                ('pruebas_resultado', models.JSONField(db_column='prb_cal_rel_resultado', verbose_name='Test results')),
                ('pruebas_tolerancia', models.TextField(db_column='prb_cal_rel_tolerancia', verbose_name="Test's tolerance")),
                ('pruebas_condicion_respuesta', models.TextField(db_column='prb_cal_rel_condicion_respuesta', verbose_name="Test's condition")),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('operacion', models.ManyToManyField(through='Tests.Prb_Cal_Opr_Model', to='Operations.operacionesmodel')),
            ],
            options={
                'db_table': 'tests_PruebaCalculoRelacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaOpcionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_opc_id', primary_key=True, serialize=False)),
                ('pruebas_opciones', models.JSONField(db_column='prb_opc_resultado', verbose_name='Test results')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_PruebaOpciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaVariableModel',
            fields=[
                ('id', models.BigAutoField(db_column='var_id', primary_key=True, serialize=False)),
                ('nombre_variable', models.CharField(db_column='var_nombre', max_length=255, verbose_name='Nombre de la variable')),
                ('rango_variable', models.IntegerField(db_column='var_rango', verbose_name='Rango de valores que puede tomar esta variable')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'tests_PruebaVariables',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebasModel',
            fields=[
                ('id', models.BigAutoField(db_column='prb_id', primary_key=True, serialize=False)),
                ('pruebas_titulo', models.CharField(db_column='prb_titulo', max_length=255, unique=True, verbose_name='Test name')),
                ('pruebas_contexto', models.TextField(blank=True, db_column='prb_contexto', null=True, verbose_name='Test context')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('calculo', models.ManyToManyField(through='Tests.Prb_Calculo_Model', to='Tests.pruebacalculomodel')),
                ('calculo_relacion', models.ManyToManyField(through='Tests.Prb_Calculo_Model', to='Tests.pruebacalculorelacionmodel')),
                ('opcion', models.ManyToManyField(through='Tests.Prb_Calculo_Model', to='Tests.pruebaopcionesmodel')),
            ],
            options={
                'db_table': 'tests_Pruebas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pruebacalculomodel',
            name='prueba_relacion',
            field=models.ManyToManyField(through='Tests.Prb_PrbRelacion_Model', to='Tests.pruebacalculorelacionmodel'),
        ),
        migrations.AddField(
            model_name='prb_prbrelacion_model',
            name='prueba_calculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prb_prbrelacion_model',
            name='prueba_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculorelacionmodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='calculo_relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculorelacionmodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebaopcionesmodel'),
        ),
        migrations.AddField(
            model_name='prb_calculo_model',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebasmodel'),
        ),
        migrations.CreateModel(
            name='Prb_Cal_Opr_Val_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCalOpr_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('calculo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.prb_cal_opr_model')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebavariablemodel')),
            ],
            options={
                'db_table': 'tests_prueba_calculo_operaciones_variables',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='calculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculomodel'),
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='calculo_relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tests.pruebacalculorelacionmodel'),
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operations.operacionesmodel'),
        ),
        migrations.AddField(
            model_name='prb_cal_opr_model',
            name='variables',
            field=models.ManyToManyField(through='Tests.Prb_Cal_Opr_Val_Model', to='Tests.pruebavariablemodel'),
        ),
    ]
