# Generated by Django 4.1.1 on 2022-09-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prb_calculo_model',
            table='tests_prueba_tipos',
        ),
    ]
