# Generated by Django 4.1.1 on 2022-09-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0002_alter_prb_calculo_model_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prb_cal_opr_val_model',
            old_name='calculo_operacion',
            new_name='operaciones_calculo',
        ),
        migrations.CreateModel(
            name='Prb_Cal_Opr_relacion_Val_Model',
            fields=[
                ('id', models.BigAutoField(db_column='PrbCalOprRelVal_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('operacion_echa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.prb_cal_opr_model')),
                ('operacion_nueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.prb_cal_opr_val_model')),
            ],
            options={
                'db_table': 'tests_prueba_calculo_operacion_relacion_variables',
                'ordering': ['id'],
            },
        ),
    ]
