# Generated by Django 4.0.7 on 2022-09-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolsModel',
            fields=[
                ('id', models.BigAutoField(db_column='prt_id', primary_key=True, serialize=False)),
                ('nombre_protocolo', models.CharField(db_column='prt_name', max_length=255, unique=True, verbose_name='Tube brand')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'protocols_Protocolos',
                'ordering': ['id'],
            },
        ),
    ]
