# Generated by Django 4.0.7 on 2022-09-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal_Med_Model',
            fields=[
                ('id', models.BigAutoField(db_column='CalMed_id', primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'companymachine_calibraciones_medidores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalibracionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='cal_id', primary_key=True, serialize=False)),
                ('fecha_calibracion', models.DateField(db_column='cal_fecha_calibracion', verbose_name='Calibration date')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'companymachine_Calibraciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedidoresModel',
            fields=[
                ('id', models.BigAutoField(db_column='med_id', primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='med_marca_medidor', max_length=255, verbose_name='Meter brand')),
                ('modelo', models.CharField(db_column='med_modelo_medidor', max_length=255, verbose_name='Meter model')),
                ('serie', models.CharField(db_column='med_serie_medidor', max_length=255, unique=True, verbose_name='Meter series')),
                ('is_enabled', models.BooleanField(default=True)),
                ('crated_at', models.DateTimeField(editable=False)),
                ('members', models.ManyToManyField(through='CompanyMachine.Cal_Med_Model', to='CompanyMachine.calibracionesmodel')),
            ],
            options={
                'db_table': 'companymachine_Medidores',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cal_med_model',
            name='calibracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.calibracionesmodel'),
        ),
        migrations.AddField(
            model_name='cal_med_model',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel'),
        ),
    ]
