# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal_Med_Model',
            fields=[
                ('id', models.BigAutoField(db_column='CalMed_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'companymachine_calibraciones_medidores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalibracionesModel',
            fields=[
                ('id', models.BigAutoField(db_column='cal_id', primary_key=True, serialize=False)),
                ('fecha_calibracion', models.DateField(db_column='cal_fecha_calibracion', verbose_name='Calibration date')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'companymachine_Calibraciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedidoresModel',
            fields=[
                ('id', models.BigAutoField(db_column='med_id', primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='med_marca_medidor', max_length=255, verbose_name='Meter brand')),
                ('modelo', models.CharField(db_column='med_modelo_medidor', max_length=255, verbose_name='Meter model')),
                ('serie', models.CharField(db_column='med_serie_medidor', max_length=255, unique=True, verbose_name='Meter series')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'companymachine_Medidores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Calibraciones_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Medidores_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('registerd_at', models.DateTimeField(blank=True, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel')),
            ],
        ),
    ]
