# Generated by Django 4.1.1 on 2022-10-11 05:41

import User.models
from django.db import migrations, models
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal_Med_Model',
            fields=[
                ('id', models.BigAutoField(db_column='CalMed_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'companymachine_calibraciones_medidores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalibracionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='cal_id', primary_key=True, serialize=False)),
                ('fecha_calibracion', models.DateField(db_column='cal_fecha_calibracion', verbose_name='Calibration date')),
            ],
            options={
                'db_table': 'companymachine_Calibraciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCalibracionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='cal_id', db_index=True)),
                ('fecha_calibracion', models.DateField(db_column='cal_fecha_calibracion', verbose_name='Calibration date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMedidoresModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='med_id', db_index=True)),
                ('marca', models.CharField(db_column='med_marca_medidor', max_length=255, verbose_name='Meter brand')),
                ('modelo', models.CharField(db_column='med_modelo_medidor', max_length=255, verbose_name='Meter model')),
                ('serie', models.CharField(db_column='med_serie_medidor', db_index=True, max_length=255, verbose_name='Meter series')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedidoresModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='med_id', primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='med_marca_medidor', max_length=255, verbose_name='Meter brand')),
                ('modelo', models.CharField(db_column='med_modelo_medidor', max_length=255, verbose_name='Meter model')),
                ('serie', models.CharField(db_column='med_serie_medidor', max_length=255, unique=True, verbose_name='Meter series')),
                ('members', models.ManyToManyField(through='CompanyMachine.Cal_Med_Model', to='CompanyMachine.calibracionesmodel')),
            ],
            options={
                'db_table': 'companymachine_Medidores',
                'ordering': ['id'],
            },
        ),
    ]
