# Generated by Django 4.1.1 on 2022-10-11 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedidoresmodel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcalibracionesmodel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cal_med_model',
            name='calibracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.calibracionesmodel'),
        ),
        migrations.AddField(
            model_name='cal_med_model',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel'),
        ),
    ]
