# Generated by Django 4.1.1 on 2022-10-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_medidores_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_calibraciones_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.calibracionesmodel'),
        ),
        migrations.AddField(
            model_name='user_calibraciones_model',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medidoresmodel',
            name='members',
            field=models.ManyToManyField(through='CompanyMachine.Cal_Med_Model', to='CompanyMachine.calibracionesmodel'),
        ),
        migrations.AddField(
            model_name='medidoresmodel',
            name='user',
            field=models.ManyToManyField(through='CompanyMachine.User_Medidores_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibracionesmodel',
            name='user',
            field=models.ManyToManyField(through='CompanyMachine.User_Calibraciones_Model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cal_med_model',
            name='calibracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.calibracionesmodel'),
        ),
        migrations.AddField(
            model_name='cal_med_model',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMachine.medidoresmodel'),
        ),
    ]
