# Generated by Django 3.2.6 on 2022-09-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMachine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cal_med_model',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='calibracionesmodel',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='medidoresmodel',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
