# Generated by Django 4.1.1 on 2022-09-28 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMachine', '0003_user_medidores_model_user_calibraciones_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal_med_model',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
