# Generated by Django 4.1.2 on 2022-10-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMachine', '0003_alter_historicalcalibracionesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidoresmodel',
            options={},
        ),
    ]
