# Generated by Django 4.1.2 on 2022-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMachine', '0004_alter_medidoresmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedidoresmodel',
            name='title',
            field=models.CharField(db_column='med_titulo_medidor', default='da', max_length=255, verbose_name='Meter title'),
        ),
        migrations.AddField(
            model_name='medidoresmodel',
            name='title',
            field=models.CharField(db_column='med_titulo_medidor', default='da', max_length=255, verbose_name='Meter title'),
        ),
    ]
