# Generated by Django 4.1.2 on 2022-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMachine', '0005_historicalmedidoresmodel_title_medidoresmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedidoresmodel',
            name='title',
            field=models.CharField(db_column='med_titulo_medidor', max_length=255, verbose_name='Meter title'),
        ),
        migrations.AlterField(
            model_name='medidoresmodel',
            name='title',
            field=models.CharField(db_column='med_titulo_medidor', max_length=255, verbose_name='Meter title'),
        ),
    ]
