# Generated by Django 4.1.5 on 2023-01-27 19:38

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.BigAutoField(db_column='ss_id', editable=False, primary_key=True, serialize=False)),
                ('ubicacion', models.JSONField(db_column='ss_ubicacion', editable=False, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authenticacion_Sesiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSesionesModel',
            fields=[
                ('is_enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('id', models.BigIntegerField(blank=True, db_column='ss_id', db_index=True, editable=False)),
                ('ubicacion', models.JSONField(db_column='ss_ubicacion', editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': User.models.User,
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
