# Generated by Django 4.1.5 on 2023-01-27 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_sesionesmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionesmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesionesmodel',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
