# Generated by Django 4.1.5 on 2023-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_historicalsesionesmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsesionesmodel',
            name='ubicacion',
            field=models.JSONField(db_column='ss_ubicacion', null=True),
        ),
        migrations.AlterField(
            model_name='sesionesmodel',
            name='ubicacion',
            field=models.JSONField(db_column='ss_ubicacion', null=True),
        ),
    ]
