# Generated by Django 4.1.5 on 2023-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_historicalsesionesmodel_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsesionesmodel',
            name='id',
            field=models.BigIntegerField(blank=True, db_column='ss_id', db_index=True),
        ),
        migrations.AlterField(
            model_name='sesionesmodel',
            name='id',
            field=models.BigAutoField(db_column='ss_id', primary_key=True, serialize=False),
        ),
    ]
