# Generated by Django 4.1.5 on 2023-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_historicaluser_firma_alter_user_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firma',
            field=models.ImageField(blank='', default='', null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='', default='', null=True, upload_to='reports/'),
        ),
    ]
